package cr.ac.una.turnos.common.enums;

public enum TipoMensaje {
    LOGIN,
    LOGOUT,

    OBTENER_SERVICIOS,
    GENERAR_TURNO,

    SOLICITAR_SIGUIENTE_TURNO,
    LLAMAR_TURNO,
    INICIAR_ATENCION,
    FINALIZAR_ATENCION,
    RECLAMAR_TURNO,

    OBTENER_VENTANILLAS,
    CAMBIAR_ESTADO_VENTANILLA,

    ACTUALIZAR_PANTALLA,

    OBTENER_USUARIOS,
    OBTENER_FUNCIONARIOS,
    OBTENER_REPORTES,

    ERROR
}